name: Growfolio
options:
  bundleIdPrefix: com.growfolio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    SWIFT_STRICT_CONCURRENCY: complete
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

packages: {}

targets:
  Growfolio:
    type: application
    platform: iOS
    sources:
      - path: Growfolio
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Growfolio/Resources
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: "Growfolio"
        PRODUCT_BUNDLE_IDENTIFIER: com.growfolio.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies: []

  GrowfolioTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GrowfolioTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.growfolio.tests
    dependencies:
      - target: Growfolio

  GrowfolioUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: GrowfolioUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.growfolio.uitests
    dependencies:
      - target: Growfolio

schemes:
  Growfolio:
    build:
      targets:
        Growfolio: all
        GrowfolioTests: [test]
        GrowfolioUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - GrowfolioTests
        - GrowfolioUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
